M48
; DRILL file {KiCad 9.0.6} date 2026-01-02T16:59:04-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-02T16:59:04-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X75.0Y-95.0
T2
X75.044Y-144.0
X133.0Y-95.0
X133.044Y-144.0
M30
